//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProbCut.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PricingData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PricingData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProbCut.Resources.PricingData", typeof(PricingData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string BeardLineUp {
            get {
                return ResourceManager.GetString("BeardLineUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string BeardTrim {
            get {
                return ResourceManager.GetString("BeardTrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 700.
        /// </summary>
        public static string Eyebrows {
            get {
                return ResourceManager.GetString("Eyebrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        public static string HairColoring {
            get {
                return ResourceManager.GetString("HairColoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string HairCurling {
            get {
                return ResourceManager.GetString("HairCurling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150.
        /// </summary>
        public static string HaircutChildren {
            get {
                return ResourceManager.GetString("HaircutChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 300.
        /// </summary>
        public static string HaircutMen {
            get {
                return ResourceManager.GetString("HaircutMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string HaircutWomen {
            get {
                return ResourceManager.GetString("HaircutWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800.
        /// </summary>
        public static string HairDrying {
            get {
                return ResourceManager.GetString("HairDrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 600.
        /// </summary>
        public static string HairShading {
            get {
                return ResourceManager.GetString("HairShading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string LineUp {
            get {
                return ResourceManager.GetString("LineUp", resourceCulture);
            }
        }
    }
}
