using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Asocijacije
{
  public class ListaAss
    {
       public  List<Ass> A = new List<Ass>();
        public  Ass vrati(int i)
        {
           
            return A[i];
        }
        public ListaAss()
        {
            A.Add(new Ass("FARMACIJA", "GARIC", "DRVO", "BFF", new List<string> { "Ceki", "CEKI", "ceki", "cerovina",
                "CEROVINA" },
                "EMISIJA", "B92", "POLITIKA", "PODSMEH", new List<string> { "ZORAN KESIC", "KESIC" }, "DOBAR", "SUNCE",
                "DOSADAN",
                "KISA", new List<string> { "DAN", "dan", "dn" }, "PESAK", "KAZALJKA", "RUKA", "DZEP", new List<string> {
                    "SAT", "sat" },
                new List<string> { "24" }));
            A.Add(new Ass("KISA", "DOBA", "LISCE", "ZUTO", new List<string> { "JESEN", "jesen", "Jesen" }, "RODJENDAN", "MIRIS", "D&G", "VERSACE", new List<string> { "PARFEM", "Parfem", "parfem", "miris", "MIRIS" },
                "PEPKO", "KOSULJA", "DZEMPER", "MAJICA", new List<string> { "SPRINGFILD", "Springfield", "springfild" }, "BOJA", "KOSA", "OKO", "NEBO", new List<string> { "PLAVI", "PLAVO", "plavi", "plavo", "Plavo" }, new List<string> { "KAPUTIC", "kaputic", "kaput" }));

            A.Add(new Ass("CNS", "PAMET", "MASA", "SINAPSA", new List<string> { "MOZAK", "Mozak", "mozak"
            },
              "STIT", "BORBA", "RIM", "KOLOSEUM", new List<string> { "GLADIJATOR", "gladijator","Gladijator" }, "PRELEP", "JELKA",
              "USTA",
              "ZUBI", new List<string> { "OSMEH", "osmeh", "SMEH" }, "REDITELJ", "GLUMAC", "AKCIONI", "TITANIK", new List<string> {
                    "FILM", "film" },
              new List<string> { "BLISTAVI UM","Blistavi um" }));

            A.Add(new Ass(
                "JAGODE",
                "VETAR", 
                "SVINJA",
                "ZAPAD", 
                new List<string> { "DIVLJI", "Divlje", "divlji"
            },
            "CUVANJE", 
            "LJUDI", 
            "ZIVI", 
            "LJUBIMAC",
            new List<string> { "PITOMI", "pitomo", "Pitom" }, 
            "PLAVE",
            "ZELENE",
            "BRAON",
            "POGLED",
            new List<string> { "OCI", "OKO", "oci" }, 
            "DETELINA", 
            "MINIVAL", 
            "FRIZER", 
            "PRAMEN", new List<string> { "KOSA", "kosa" },

            new List<string> { "KESTEN", "kesteni" }));

            A.Add(new Ass(
              "BILJKA",
              "BROS",
              "MRZNJA",
              "HEMIJSKA",
              new List<string> { "KAKTUS", "Kaktusi", "kaktus"
          },
          "SRBIJA",
          "SNEG",
          "KUTAK",
          "KINA",
          new List<string> { "NOVA GODINA", "Nova Godina"},
          "SANJA",
          "CAR LAZAR",
          "GRAD",
          "NAPREDAK",
          new List<string> { "KRUSEVAC" },
          "NOVAC",
          "ZATVOR",
          "BANKA",
          "PLJACKA", new List<string> { "LOPOV", "PLJACKAS" },

          new List<string> { "CARAPA", "CARAPANI" }));

            A.Add(new Ass(
              "UGLJENIK",
              "POLA",
              "OCENA",
              "GOLF",
              new List<string> { "6", "SEST", "SESTICA"
          },
          "ISLAM",
          "POLU",
          "12",
          "9",
          new List<string> { "MESECI", "MESEC", "MESECIMA" },
          "NOVA",
          "DOBRA",
          "PRESTUP",
          "RODNA",
          new List<string> { "GODINA", "GODINAMA", "GODIN" },
          "ZBOG TEBE",
          "O TEBI",
          "RUZA",
          "ORHIDEJA", new List<string> { "PESMA", "pesma" },

          new List<string> { "ZUTE DUNJE", "ZUTE DUNJEM" }));

            A.Add(new Ass(
              "POVRACANJE",
              "PARA",
              "DASKA",
              "STVARI",
              new List<string> { "PEGLA", "PEGLANJE", "PEGLAMA"
          },
          "GUMA",
          "BASTA",
          "VODA",
          "NAVODNJAVANJE",
          new List<string> { "CREVO", "CREVCE", "CREVA" },
          "REN",
          "KECAP",
          "CILI",
          "PAPRIKA",
          new List<string> { "LJUTA", "LJUTI", "LJUTKO" },
          "GASOVI",
          "MAHUNARKE",
          "ZRNA",
          "CORBA", new List<string> { "PASULJ", "pasulj" },

          new List<string> { "KOBASICA", "KOBASICE" }));

            A.Add(new Ass(
              "TEMPO",
              "IDEA",
              "MAXI",
              "LIDL",
              new List<string> { "PRODAVNICA", "PRODAVNICE"          },
          "ALARM",
          "DOBRO",
          "PETA0",
          "MARGARIN",
          new List<string> { "JUTRO", "JUTRA", "JUTRE" },
          "ULICA",
          "IZLET",
          "RAD",
          "PRAZNIK",
          new List<string> { "PRVI MAJ", "1. MAJ", "1 MAJ" },
          "CIRKUS",
          "SATOR",
          "SPAVANJE",
          "NAMESTANJ",new List<string> { "SATOR", "SATORI" },

          new List<string> { "URANAK" , "URANCI" }));

            A.Add(new Ass(
              "SAH",
              "TENIS",
              "FUDBAL",
              "KOSARKA",
              new List<string> { "KLUB", "KLUBOVI", "CLUB"
          },
          "RESTORAN",
          "SKADARLIJA",
          "BISER",
          "MEZE",
          new List<string> { "KAFANA", "KAFANICA", "BIRTIJA" },
          "DJAKUS",
          "OPSTINA",
          "PRASICI",
          "CECA",
          new List<string> { "ZITORADJA", "ZIT", "ZITRDJE" },
          "ZOVA",
          "LIMUNADA",
          "KOLACI",
          "SLADOLED", new List<string> { "POSLASTICARA", "POSLASTICARNCIA" },

          new List<string> { "DEJAN", "DISKE","DISIC" }));

            A.Add(new Ass(
            "SVE ZA",
            "ONO KAO",
            "SRCE",
            "PEPA",
            new List<string> { "LJUBAV", "SRCE", "ROMANTIKA"
        },
        "AUTO",
        "ZEMLJANI",
        "SLEPI",
        "VIA",
        new List<string> { "PUT", "PUTOVANJE", "PUTOVATI" },
        "CRTANJE",
        "PEJZAZ",
        "FAKULTET",
        "JELKA",
        new List<string> { "ARHITEKTURA", "ARH", "ARHITEKTURS" },
        "KENGUR",
        "LETOVANJE",
        "RANAC",
        "PRADA", new List<string> { "TORBA", "TASNA" },

        new List<string> { "KOFER"}));

            A.Add(new Ass(
          "SLIKA",
          "PAPIR",
          "OLOVKA",
          "KAKTUS",
          new List<string> { "CRTEZ", "SLIKA", "CRTANJE"
      },
      "ZGRADA",
      "PROJEKTOVANJE",
      "RACUNARA",
      "MOST",
      new List<string> { "ARHITEKTURA" },
      "ZUTE DUNJE",
      "MOJA",
      "PISANJE",
      "RECITOVANJE",
      new List<string> { "PESMA", "PESME", "PJESMA" },
      "GAF",
      "MEDICINA",
      "ELEKTRONSKI",
      "PRAVNI", new List<string> { "FAKULTET", "FAKS" },

      new List<string> { "UMETNOST" }));

            A.Add(new Ass(
          "MED",
          "KRILA",
          "ZAOKA",
          "JELKA",
          new List<string> { "PCELICA", "PCELA", "PCELE"
      },
      "PROTEZA",
      "TEGLA",
      "NAOCARE",
      "SKOLA",
      new List<string> { "STREBER", "STREBERI", "STREBANJE" },
      "BELO",
      "AU",
      "POLUGA",
      "ZUTO",
      new List<string> { "ZLATO", "ZLATAN", "ZLATNI" },
      "UZBUNA",
      "TRUD",
      "CUVANJE",
      "PEPA", new List<string> { "PAZNJA", "PAZITI" },

      new List<string> { "VREDAN","VREDNO","VREDNIC" }));

            A.Add(new Ass(
          "MAKAZE",
          "APLKACIJA",
          "SALON",
          "MINIVAL",
          new List<string> { "FRIZERA", "FRIZERAJ", "FRIZER"
      },
      "TESLA",
      "DASKA",
      "UVO",
      "EKSER",
      new List<string> { "CEKIC", "CUK", "MACOLA" },
      "CUVANJE",
      "GOVEDO",
      "KRAVA",
      "SELO",
      new List<string> { "STOKA", "KRAVA" },
      "OKO",
      "KOSA",
      "NEBO",
      "KOSA", new List<string> { "PLAV", "PLAVA","PLAVO","PLAVI" },

      new List<string> { "TOR" }));

            A.Add(new Ass(
          "REP",
          "KLADIONICA",
          "KRALJ",
          "GRIVA",
          new List<string> { "LAV", "LAVOVI"
      },
      "ODMOR",
      "ICA",
      "NEDELJA",
      "SUBOTA",
      new List<string> { "VIKEND", "NEDELJA", "SUBOTA" },
      "SUDOVI",
      "ZIVOTINJA",
      "RIBANJE",
      "VODA",
      new List<string> { "SUNDJER", "SUNDJERI" },
      "PAPRIKE",
      "VAMPIR",
      "BELI",
      "CRNI", new List<string> { "LUK", "PRAZILUK" },

      new List<string> { "PLJESKAVICA","PLJESKA","PLJESKAVICE" }));


            

            A.Add(new Ass(
          "RODJENJE",
          "SMRT",
          "GOLI",
          "VITA",
          new List<string> { "ZIVOT", "ZIVOTI"
      },
      "NEZIVA PRIRODA",
      "MATEMATIKA",
      "LIKOVNO",
      "CORPUS",
      new List<string> { "PREDMET", "PREDMETI", "SUBJEKT" },
      "PINK",
      "RTS",
      "ORGANIZACIJA",
      "PLAN",
      new List<string> { "PROGRAM", "PROGRAMI" },
      "DO",
      "SOL",
      "MI",
      "FA", new List<string> { "RE"},

      new List<string> { "REVITALIZACIJA", "REVIT", "REVITA" }));

            A.Add(new Ass(
         "SMOR",
         "DOSADA",
         "NERVOZA",
         "DEBEO",
         new List<string> { "PEPIC", "PEPKO"
     },
     "TRN",
     "MAJKA",
     "SI BILA",
     "COLIC",
     new List<string> { "RUZICA", "RUZA", "RUSKA" },
     "OD BOGA",
     "MINUS",
     "SAOBRACAJ",
     "PLUS",
     new List<string> { "ZNAK", "ZNACI" },
     "JAKO",
     "JOS OVO...",
     "UBISTVO",
     "CA", new List<string> { "SAMO" },

     new List<string> { "STRELA", "STRELAC", "STRELCI" }));

            A.Add(new Ass(
       "CRNI",
       "BELI",
       "REZANI",
       "KRUH",
       new List<string> { "HLEB", "HLEBA"
   },
   "GOL",
   "SPORT",
   "SUDIJA",
   "LOPTA",
   new List<string> { "FUDBAL", "FUDBALICA", "FUDBAL" },
   "!",
   "ZAPOVEDNI",
   "NAREDBA",
   "POBEDE",
   new List<string> { "IMPERATIV", "IMPERATIVNO" },
   "KVASAC",
   "KORA",
   "PICA",
   "PECIVO", new List<string> { "TESTO" },

   new List<string> { "MESI", "MESSI", "MESII" }));

            A.Add(new Ass(
       "BICIKL",
       "IZUM",
       "GLUP",
       "AUTO",
       new List<string> { "TOCAK", "TOCKOVI"
   },
   "EMINEM",
   "KONJ",
   "KOSA",
   "MUZIKA",
   new List<string> { "REP", "RAP", "REP" },
   "RACUNAR",
   "PC",
   "PROCESOR",
   "PROGRAM",
   new List<string> { "KOMPJUTER", "RACUNAR" },
   "RUPE",
   "GAUDA",
   "MLEKO",
   "SVAJCARSKA", new List<string> { "SIR","SIRA" },

   new List<string> { "MIS", "PACOV", "MISEVI" }));

            A.Add(new Ass(
       "PROJEKTOVANJE",
       "UMETNOST",
       "JELKA",
       "FAKULTET",
       new List<string> { "ARHITEKTURA", "ARH"
   },
   "TAJNA VECERA",
   "BOJA",
   "CETKICA",
   "MONALIZA",
   new List<string> { "SLIKA", "CRTEZ", "SLIKANJE" },
   "KONTURA",
   "PAPIR",
   "OLOVKA",
   "KAKTUS",
   new List<string> { "CRTEZ", "CRTANJE" },
   "BILJKE",
   "ZIVOTINJE",
   "ZELENA",
   "EKOLOGIJA", new List<string> { "PRIRODA","PRIRODNA","PRIRODNO" },

   new List<string> { "PEJZAZ", "PEJZAZNA" }));

            A.Add(new Ass(
       "PRISON BREAK",
       "PRIJATELJI",
       "SERLOK",
       "GOT",
       new List<string> { "SERIJA", "SERIJE"
   },
   "SVETLOST",
   "POGACA",
   "TOPLOTA",
   "ZVEZDA",
   new List<string> { "SUNCE" },
   "PIRINIJE",
   "APENINI",
   "PELEPONEZ",
   "SKANDINAVSKO",
   new List<string> { "POLUOSTRVO" },
   "NIS",
   "KROJAC",
   "RADNJE",
   "TELENOR", new List<string> { "KALCA" },

   new List<string> { "SENKE NAD BALKANOM" }));

            A.Add(new Ass(
           "DIJAGRAM",
           "ZLATO",
           "GOSPODAR",
           "ANDJELA",
           new List<string> { "PRSTEN", "PRSTENI"
       },
       "ZIMA",
       "HIGIJENA",
       "SPORET",
       "CRVENE",
       new List<string> { "RUKAVICE", "RUKAVICA"},
       "OVCA",
       "TORTA",
       "CRKVA",
       "VRATA",
       new List<string> { "ZVONO", "ZVONA" },
       "OTMICA",
       "VUCA",
       "CVOR",
       "VEZATI", new List<string> { "KONOPCI","KONOPAC" },

       new List<string> { "RING" }));

            A.Add(new Ass(
       "KUVANJE",
       "ZRNA",
       "SOLJA",
       "MLEKO",
       new List<string> { "KAFA"
   },
   "KAPIJA",
   "ZELUDAC",
   "TRAVA",
   "HRANA",
   new List<string> { "VARENJE",  "VARITI" },
   "OCI",
 "PASKA",
   "BAR",
   "NERVNI",
   new List<string> { "PRITISAK", "PRITISKI" },
   "SLON",
   "ZVUK",
   "SKOLJKA",
   "CULO", new List<string> { "USI","UVO" },

   new List<string> { "APARAT", "APARATURA", "APARATI" }));


            A.Add(new Ass(
       "MOTOR",
       "SUPLJA",
       "VELIKA",
       "SECER",
       new List<string> { "GLAVA"
   ,"GLAVAN"},
   "FRIZER",
   "SRP",
   "DLAKA",
   "LIVADA",
   new List<string> { "KOSA", "KOSITI" },
   "JELKA",
 "NAPREDAK",
   "POJAS",
   "SIROK",
   new List<string> { "RAMENA", "RAME" },
   "POTOK",
   "PARK",
   "PESNICE",
   "DOBOS", new List<string> { "BUBANJ" },

   new List<string> { "TUS", "TUSIRATI"}));

            A.Add(new Ass(
      "NAPORAN",
      "DOSADAN",
      "DEBEO",
      "GLUP",
      new List<string> { "PEPIC"
   ,"PEPKO"},
  "ROSTILJ",
  "GURMAN",
  "LEPINJA",
  "LUK",
  new List<string> { "PLJESKAVICA", "PLJESKA" },
  "HISAR",
"DISICI",
  "JUG BOGDAN",
  "MAGAREVO",
  new List<string> { "PROKUPLJE", "PK" },
  "SIDRO",
  "SPANAC",
  "OLIVA",
  "BADZA", new List<string> { "POPAJ" },

  new List<string> { "PERA ZDERA" }));

            A.Add(new Ass(
      "MOTO",
      "KOLA",
      "MAT",
      "PILOT",
      new List<string> { "AUTO"
   ,"AUTOMATSKO"},
  "KOSARKA",
  "TEST",
  "ISPIT",
  "DOZVOLA",
  new List<string> { "POLAGANJE", "POLAGATI" },
  "SMOLA",
"SISARKE",
  "CETINAR",
  "NOVA GODINA",
  new List<string> { "JELKA", "JELA","JELKIC" },
  "R",
  "UNAZAD",
  "PARKIRANJE",
  "BRZINA", new List<string> { "RIKVERC" },

  new List<string> { "RETROVIZOR" }));

            A.Add(new Ass(
      "ZVUK",
      "CULO",
      "APARAT",
      "SKOLJKA",
      new List<string> { "UVO"
   ,"USI"},
  "MERENJE",
  "SO",
  "SEMENKE",
  "SUNCE",
  new List<string> { "SUNCOKRETI", "SUNCOKRET" },
  "VETRENJACA",
"KLOMPA",
  "AMSTERDAM",
  "NIZOZEMSKA",
  new List<string> { "HOLANDIJA" },
  "DJANI",
  "BRENA",
  "LUKAS",
  "CORBA", new List<string> { "PEVAC","PEVACI" },

  new List<string> { "VAN GOG" }));

            A.Add(new Ass(
      "SO",
      "CRNO",
      "ZUTO",
      "CRVENO",
      new List<string> { "MORE"
   ,"MORA"},
  "ORHIDEJA",
  "PIDZAMA",
  "PESMA",
  "BOZIC",
  new List<string> { "POKLON", "POKLONI" },
  "STEPENICE",
"JELKIC",
  "TAKMICENJE",
  "SKOLA",
  new List<string> { "CICKOVA", "CICKO" },
  "VISIBABA",
  "TUCAK",
  "BILJKA",
  "RUZA", new List<string> { "CVET","CVETIC" },

  new List<string> { "LJUBICICA"}));

            A.Add(new Ass(
      "RACUN",
      "KUCA",
      "RED",
      "PRODAVNICA",
      new List<string> { "KASA"
   ,"KASE"},
  "DETELINA",
  "PRAMEN",
  "FARBA",
  "DLAKA",
  new List<string> { "KOSA", "KOSITI" },
  "TRBUSNJACI",
"MATEMATIKA",
  "TRENING",
  "SKLEK",
  new List<string> { "VEZBANJE", "VEZBATI" },
  "MUSICE",
  "OHO",
  "SMOLA",
  "MED", new List<string> { "LEPAK" },

  new List<string> { "TRAKA", "TRAKE" }));

            A.Add(new Ass(
      "BROS",
      "RODJENDAN",
      "NOVA GODINA",
      "PIDZAMA",
      new List<string> { "POKLON"
   ,"POKLONI"},
  "SPORET",
  "SUD",
  "KUVANJE",
  "KUPUS",
  new List<string> { "LONAC" },
  "PRA",
"MARICA",
  "LJUBINKA",
  "KOSANA",
  new List<string> { "BABA", "BABE" },
  "PLAVI",
  "VAGON",
  "PRUGA",
  "LOKOMOTIVA", new List<string> { "VOZ" },

  new List<string> { "ALIESKPRES", "ALI EKSPRES" }));

            A.Add(new Ass(
      "LEDJA",
      "SALON",
      "ZEN",
      "PEPIC",
      new List<string> { "MASAZA"
   ,"MASIRATI"},
  "DETELINA",
  "SENO",
  "TELE",
  "MILKA",
  new List<string> { "KRAVA", "KRAVE" },
  "PESAK",
"KRALJICA",
  "KRALJ",
  "KONJ",
  new List<string> { "FIGURA", "FIGURE" },
  "SMUK",
  "KOBRA",
  "OTROV",
  "PITON", new List<string> { "ZMIJA" ,"ZMIJE" },

  new List<string> { "MLEKO ZA TELO","MLEKO" }));

            A.Add(new Ass(
   "TESLA",
   "TORANJ",
   "PILOT",
   "KRILA",
   new List<string> { "AVION"
   ,"AVIONI"},
"DIM",
"PROZOR",
"TUS",
"POZORISTE",
new List<string> { "ZAVESA", "ZAVESE" },
"PEPIC",
"KOSULJICA",
"POLJE",
"PROLECE",
new List<string> { "SPRINGFILD", "SPRINGFIELD" },
"NARCIS",
"LEPOTICA",
"DZEPNO",
"KUPATILO", new List<string> { "OGLEDALO", "OGLEDALCE" },

new List<string> { "KABINA" }));
            A.Add(new Ass(
   "SPRAT",
   "ISPOD",
   "STEPENICE",
   "GORE",
   new List<string> { "DOLE"
   ,"DONJI SPRAT"},
"BELO",
"BIOSKOP",
"FILM",
"ULJE",
new List<string> { "PLATNO" },
"MEMBRANA",
"BERLIN",
"PLAC",
"KINA",
new List<string> { "ZID" },
"NJE",
"MONALIZA",
"CRTEZ",
"BOJA", new List<string> { "SLIKA", "SLIKANJE" },

new List<string> { "GOBLEN" }));

            A.Add(new Ass(
   "IJA",
   "PRAVDA",
   "VRHOVNI",
   "APELACIONI",
   new List<string> { "SUD"
   ,"SUDIJA"},
"STRELAC",
"OVAN",
"JARAC",
"BIK",
new List<string> { "HOROSKOP" },
"TEZGA",
"CVET",
"POVRCE",
"BULEVAR",
new List<string> { "PIJACA", "PIJAC" },
"VEZBANJE",
"SIPKA",
"TERETANA",
"SUDOVI", new List<string> { "TEGOVI" },

new List<string> { "VAGA" }));


    


            A.Add(new Ass(
"LJULJANJE",
"PRSKANJE",
"CAIR",
"KEJ",
new List<string> { "SETANJE"
   ,"SETNJA"},
"TUGA",
"SMEH",
"BOL",
"SUZA",
new List<string> { "PLAKANJE","PLAKATI" },
"OBEZBEDJENJE",
"TAJNA",
"PAS",
"DETE",
new List<string> { "CUVANJE","CUVATI" },
"IKAD",
"ODUVEK",
"BILO KAD",
"OBECANJE", new List<string> { "ZAUVEK" },
new List<string> { "AKO TRAZIS NEKOGA" }));

            A.Add(new Ass(
"TELEVIZIJA",
"JELKIC",
"MI",
"NE",
new List<string> { "SRECA","HAPPY"
   ,"HAPPY"},
"KOLONE",
"2",
"+",
"2",
new List<string> { "4","CETIRI","CETRI" },
"SVESKA",
"BILJKA",
"TRANSPIRACIJA",
"FRANC",
new List<string> { "LIST" },
"FRIZER",
"DLAKA",
"PRAMEN",
"MINIVAL", new List<string> { "KOSA" },
new List<string> { "DETELINA","DETELINE" }));

            A.Add(new Ass(
"DOBA",
"CVETANJE",
"SUNCE",
"LASTA",
new List<string> { "PROLECE"
   ,"PROLECA"},
"GRUPA",
"PERECA",
"PUTNIK",
"SARGAN",
new List<string> { "OSAM","8" },
"DEDA",
"LJUBINKA",
"KOSANA",
"MARICA",
new List<string> { "BABA","BAKA" },
"10+8",
"20-2",
"22+20-24",
"3+15", new List<string> { "18","OSAMNAEST","OSAMNEST" },
new List<string> { "MART" }));

            A.Add(new Ass(
"ANTI",
"TROJAN",
"DNK",
"RNK",
new List<string> { "VIRUS"
   },
"KISEONIK",
"AZOT",
"PUMPA",
"PLIN",
new List<string> { "GAS" },
"AJFON",
"FIKSNI",
"MOBILNI",
"NOKIA",
new List<string> { "TELEFON" },
"LEPO",
"OBRAZI",
"USTA",
"NOS", new List<string> { "LICE" },
new List<string> { "MASKA" }));

            A.Add(new Ass(
"MOBILNA",
"FIKSNA",
"JELKA",
"ANJA",
new List<string> { "PROTEZA"
   },
"TAC",
"FIKSNI",
"MOBILNI",
"SMART",
new List<string> { "TELEFON" },
"PLOT",
"DRVENA",
"STRUJA",
"TARABE",
new List<string> { "OGRADA" },
"KISA",
"VELIKI",
"KOKTEL",
"SUNCOBRAN", new List<string> { "KISOBRAN" },
new List<string> { "ZICA","ZICE" }));

            A.Add(new Ass(
"JELKIC JE MOJ..",
"NAS",
"OKO",
"PLANETA",
new List<string> { "SVET"
   ,"SVETA"},
"ZMAJ",
"SVESKA",
"DRVO",
"WC",
new List<string> { "PAPIR" },
"RECIKLAZA",
"PRODAVNICA",
"PAPIR",
"PLASTIKA",
new List<string> { "KESA" },
"CVECE",
"KINA",
"KERAMIKA",
"DINASTIJA", new List<string> { "VAZA" },
new List<string> { "UKRAS","UKRASI" }));

            A.Add(new Ass(
"MAJSTOR",
"OBUCAR",
"PARK",
"SV SAVA",
new List<string> { "RADNJA"
   ,"POSLASTICARA"},
"SI",
"CASA",
"PESAK",
"PROZOR",
new List<string> { "STAKLO" },
"SKOLJKA",
"APARAT",
"CEPIC",
"ZVUK",
new List<string> { "USI","UVO" },
"REP",
"MACKA",
"DZERI",
"SIR", new List<string> { "MIS" },
new List<string> { "SLON" }));

            A.Add(new Ass(
"ZID",
"PLOT",
"PROZOR",
"KUCA",
new List<string> { "CIGLA"},
"ZAPALITI",
"DIM",
"PROMETEJ",
"OCI",
new List<string> { "VATRA" },
"IRINEJ",
"PAVLE",
"VASELJENA",
"CRKVA",
new List<string> { "PATRIJARH" },
"METOHIJA",
"BOJ",
"DEVOJKA",
"RAT", new List<string> { "KOSOVO" },
new List<string> { "PEC","PECKA" }));

            A.Add(new Ass(
"PUTIN",
"ST PETERBURG",
"VOLGA",
"MOSKVA",
new List<string> { "RUSIJA"},
"RENO",
"VERSAJ",
"NICA",
"PARIZ",
new List<string> { "FRANCUSKA" },
"REPUBLIKA",
"LJUDI",
"KINA",
"PESMA",
new List<string> { "NAROD","NARODNA" },
"GOT",
"FRENDS",
"BREAKING BAD",
"POBEDA", new List<string> { "SERIJA","SERIJE" },
new List<string> { "KUHINJA" }));

            A.Add(new Ass(
"SKOLA",
"IGRACKA",
"UKRAS",
"SVET",
new List<string> { "DECA"
   ,"DETE"},
"SRBIJA",
"KINA",
"31",
"DECEMBAR",
new List<string> { "NOVA GODINA" },
"SAOBRACAJ",
"STOPSHOP",
"RASKRSNICA",
"MERKATOR",
new List<string> { "KRUZNI TOK" },
"BRESKVA",
"VOCE",
"KOSKA",
"DRVO", new List<string> { "KAJSIJA" },
new List<string> { "KUTAK" }));


            A.Add(new Ass(
"JAJA",
"OBROK",
"JUTRO",
"RUCAK",
new List<string> { "DORUCAK"},
"PSENICA",
"HLEB",
"LUD",
"SMEH",
new List<string> { "BRASNO" },
"KLIP",
"AS71",
"KLASINKA",
"KOKICE",
new List<string> { "KUKURUZ" },
"MIS",
"RUPE",
"MLEKO",
"GAUDA", new List<string> { "SIR" },
new List<string> { "KACAMAK" }));

            A.Add(new Ass(
"PRAV",
"OSTAR",
"TUP",
"OPRUZEN",
new List<string> { "UGAO","UGLOVI"},
"GOLMAN",
"OKO",
"KUCA",
"MANASTIR",
new List<string> { "VRATA" },
"PROSJAK",
"BEKSUCNIK",
"NOVAC",
"ULICA",
new List<string> { "PROSJAK" },
"CUVANJE",
"ZADATAK",
"ZELJA",
"WOMEN", new List<string> { "TAJNA","SECRET" },
new List<string> { "KVAKA" }));

            A.Add(new Ass(
"OSMANLIJE",
"ANKARA",
"MORE",
"BOSFOR",
new List<string> { "TURSKA"},
"ROK",
"POP",
"ZABAVNI",
"DJANI",
new List<string> { "PEVAC" },
"SRBIJA",
"KASARNA",
"UNIFORMA",
"PUSKA",
new List<string> { "VOJSKA","VOJNICI" },
"PONOS",
"RUMENI",
"VRUCI",
"POLJUBAC", new List<string> { "OBRAZ","OBRAZI" },
new List<string> { "CUNE" }));

            A.Add(new Ass(
"4 LISTA",
"IRSKA",
"KRAVA",
"BROS",
new List<string> { "DETELINA"
   ,"DETELINE"},
"BROJ",
"TACKE",
"SESTRE",
"PAKT",
new List<string> { "TRI","3" },
"HOROSKOP",
"SAOBRACAJ",
"PITANJA",
"UZVIKA",
new List<string> { "ZNAK","ZNACI" },
"TABLIC",
"POKER",
"VOZ",
"BUS", new List<string> { "KARTE","KARTA" },
new List<string> { "TREF" }));

            A.Add(new Ass(
"FUDBAL",
"DJON",
"ADIDAS",
"NAJK",
new List<string> { "PATIKA","PATIKE"},
"DEPILACIJA",
"STRUNA",
"KOSA",
"KONJ",
new List<string> { "DLAKA","DLAKE" },
"LONDON",
"BRITANIJA",
"KRALJICA",
"PRINC",
new List<string> { "ENGLESKA" },
"NIS",
"DJAKUS",
"BEOGRAD",
"HIMNA", new List<string> { "SRBIJA","SRBIJE" },
new List<string> { "JEZIK" }));

            A.Add(new Ass(
"KORNET",
"KUGLA",
"PRELIV",
"DISKE",
new List<string> { "SLADOLED"
   ,"SLADOLEDI"},
"BRADA",
"CIST",
"SAMAR",
"RUMEN",
new List<string> { "OBRAZ","OBRAZI" },
"ZDRAVO",
"CAO",
"DOBAR DAN",
"DOVIDJENJA",
new List<string> { "POZDRAV" },
"USTA",
"VATRA",
"JEZIK",
"FRANCUSKA", new List<string> { "POLJUBAC" },
new List<string> { "CMOK" }));

            A.Add(new Ass(
"SI",
"PUSTINJA",
"IGRALISTE",
"ZRNO",
new List<string> { "PESAK"},
"ZABAVA",
"POLITIKA",
"IVAN IVANOVIC",
"ZORAN KESIC",
new List<string> { "EMISIJA" },
"FARMERKE",
"JAKNA",
"UNUTRASNJI",
"ZADNJI",
new List<string> { "DZEP" },
"PLAC",
"KINA",
"BERLIN",
"SLIKA", new List<string> { "ZID" },
new List<string> { "SAT" }));

            A.Add(new Ass(
"CNS",
"SINAPSE",
"PAMET",
"GLAVA",
new List<string> { "MOZAK"
   ,"UM"},
"PRICA",
"ZIVOT",
"KRVAVA",
"CRVENKAPA",
new List<string> { "BAJKA" },
"ZVONO",
"COKOLADA",
"DOBOS",
"VOCNA",
new List<string> { "TORTA" },
"PALMA",
"BOUNTY",
"LIKER",
"MLEKO", new List<string> { "KOKOS" },
new List<string> { "ORAH","ORASI" }));

            A.Add(new Ass(
"ZICE",
"MUSICE",
"NOVAC",
"TENIS",
new List<string> { "REKET"
   ,"REKETI"},
"SUNCE",
"TEGLA",
"DIOPTRIJA",
"STAKLO",
new List<string> { "NAOCARE" },
"PAMCENJE",
"KRATKA",
"DUGOROCNA",
"USPOMENE",
new List<string> { "MEMORIJA" },
"SAKSIJA",
"PROZOR",
"ZAVESA",
"PENDZER", new List<string> { "PROZOR" },
new List<string> { "RAM" }));

            A.Add(new Ass(
"MASKEMBAL",
"LOKNE",
"VESTACKA",
"KOSA",
new List<string> { "PERIKA"
   ,"PERIKE"},
"TOR",
"MESO",
"TESLA",
"EKSER",
new List<string> { "CEKIC","CUK" },
"PREPRICATI",
"TEKST",
"RAZUMEVANJE",
"PREVODILAC",
new List<string> { "TUMAC" },
"KUCANJE",
"SIVENJE",
"VES",
"PARNA", new List<string> { "MASINA" },
new List<string> { "SUD" }));

            A.Add(new Ass(
"LEPOTANCIC",
"ZGODNIC",
"SLATKIS",
"LJUBAV",
new List<string> { "JELKIC"
   ,"JELKA"},
"TESLA",
"PUPIN",
"NAUCNIK",
"NAGRADA",
new List<string> { "IZUM" },
"OBRAZ",
"KOMUNIZAM",
"ZVEZDA",
"KARMIN",
new List<string> { "CRVENI","CRVEN","CRVENA" },
"AUTO",
"SUDOVI",
"KOSA",
"VES", new List<string> { "PRANJE" },
new List<string> { "TEPIH" }));

            A.Add(new Ass(
"DEJAN",
"RUZICA",
"JELENA",
"ANDJELA",
new List<string> { "DISIC"
   ,"DISICI"},
"CELE KULA",
"CAIR",
"GRAD",
"TVRDJAVA",
new List<string> { "NIS" },
"KOTAO",
"STEPENICE",
"MALI",
"ISPOD",
new List<string> { "PODRUM" },
"KUCA",
"RESTORAN",
"HRANA",
"JELO", new List<string> { "SPECIJALITET" },
new List<string> { "KROMPIR" }));

            A.Add(new Ass(
"PEZO",
"KOLA",
"BMW",
"GOLF",
new List<string> { "AUTO"
   ,"AUTOMOBIL"},
"PTICE",
"JAKNA",
"MITARENJE",
"KOKOSKA",
new List<string> { "PERJE" },
"SPRAT",
"POSTELJINA",
"SPAVANJE",
"DUSKE",
new List<string> { "KREVET" },
"02",
"N2",
"CO2",
"CH4", new List<string> { "VAZDUH" },
new List<string> { "JASTUK" }));

            A.Add(new Ass(
"DJORDJEVIC",
"ZET",
"NJEMACKA",
"FRANKFURT",
new List<string> { "JOCA"
   ,"JOVICA"},
"BOJKOT",
"FARMACIJA",
"SESTRA",
"PRSTEN",
new List<string> { "ANDJELA" },
"SV JOVAN",
"SV SAVA",
"SV ALIMPIJE",
"SV NIKOLA",
new List<string> { "SLAVA" },
"TAJNA",
"NOC",
"LAGANA",
"HRANA", new List<string> { "VECERA" },
new List<string> { "MEZE" }));


            A.Add(new Ass(
"ULJE",
"PLAZA",
"DRVO",
"KOKOS",
new List<string> { "PALMA"
   ,"PALME"},
"ANANAS",
"LIMUN",
"KRUSKA",
"JABUKA",
new List<string> { "VOCE" },
"ZIVOTINJE",
"BEOGRAD",
"ZMIJE",
"LAV",
new List<string> { "ZOO VRT" },
"NIS",
"PROKUPLJE",
"DJAKUS",
"BEOGRAD", new List<string> { "GRAD" },
new List<string> { "JAGODINA" }));

            A.Add(new Ass(
"CECA",
"JEDNA JE..",
"SRPSKA",
"RUZICA",
new List<string> { "MAJKA"
   ,"MAMA"},
"DETE",
"MILO",
"VOKATIV",
"DEDA",
new List<string> { "CEDO" },
"BEBA",
"BEBISITER",
"DECA",
"CUVANJE",
new List<string> { "DADILJA" },
"LIRSKA",
"EPSKA",
"RODOLJUBIVA",
"DODOLE", new List<string> { "PESMA","PESME" },
new List<string> { "PJESMO MOJA","PESMO MOJA" }));

            A.Add(new Ass(
"ADVOKAT",
"VASA",
"IGNJAT",
"PAVLE",
new List<string> { "BRAT"
   ,"PALME"},
"CRNI DJORDJE",
"NENAD JEZDIC",
"CEDA VELJA",
"BOLE",
new List<string> { "CRNI GRUJA" },
"MANDA",
"VUK KOSTIC",
"KOJO",
"GLOGOVAC",
new List<string> { "GLUMAC","GLUMCI" },
"GEDZET",
"KLUZO",
"DETEKTIV",
"POLICIJA", new List<string> { "INSPEKTOR" },
new List<string> { "BANE TRIFUNOVIC" }));

            A.Add(new Ass(
"KRAVA",
"MIS",
"TIGAR",
"LAV",
new List<string> { "ZIVOTINJA"
   ,"ZIVOTINJE"},
"TROPSKO",
"VIC",
"VOCE",
"KONZERVA",
new List<string> { "ANANAS" },
"MIS",
"SIR",
"AUTO",
"ASFALT",
new List<string> { "RUPE","RUPA" },
"CRNO",
"CRVENO",
"SEVERNO",
"SO", new List<string> { "MORE" },
new List<string> { "SUNDJER" }));

            A.Add(new Ass(
"MOJE...",
"DAO SAM TI..",
"LJUBAV",
"JELKIC",
new List<string> { "SRCE"
   ,"SRCA"},
"CO2",
"N2",
"MASKA",
"O2",
new List<string> { "GAS","GASOVI" },
"KRIMINAL",
"RAST",
"EKONOMIJA",
"GRANA",
new List<string> { "PRIVREDA","PRIVREDNA" },
"BRAT",
"PRAVNI",
"KANCELARIJA",
"SUD", new List<string> { "ADVOKAT" },
new List<string> { "KOMORA" }));

            A.Add(new Ass(
"OKO",
"BAR",
"PASKAL",
"P",
new List<string> { "PRITISAK"
   ,"PRITISKA"},
"BRONHIJALNA",
"PLUCA",
"BOLEST",
"GUSENJE",
new List<string> { "ASTMA" },
"EVRO",
"DIZEL",
"BENZIN",
"G-DRIVE",
new List<string> { "GORIVO" },
"MOJE",
"CVOR",
"LJUBAV",
"KOMORA", new List<string> { "SRCE" },
new List<string> { "PUMPA" }));

            A.Add(new Ass(
"SLON",
"KONJ",
"MAJMUN",
"KRAVA",
new List<string> { "ZIVOTINJA"
   ,"ZIVOTINJE"},
"STABLO",
"CVET",
"LIST",
"KOREN",
new List<string> { "BILJKA","BILJKE" },
"MORE",
"ISTANBUL",
"BOSFOR",
"OSMANSKO",
new List<string> { "TURSKA","TURCI" },
"ITALIJA",
"PO",
"GUSKE",
"KOLOSEUM", new List<string> { "RIM" },
new List<string> { "CARSTVO" }));

            A.Add(new Ass(
"EKRAN",
"PROZOR",
"PESAK",
"SI",
new List<string> { "STAKLO"
   ,"STAKLENI"},
"DJAKUS",
"LESKOVAC",
"CILI",
"LJUTA",
new List<string> { "PAPRIKA" },
"SIRCE",
"ZELENA",
"VOCE",
"CEZAR",
new List<string> { "SALATA" },
"KUPUS",
"KROMPIR",
"PARADAJZ",
"VOCE", new List<string> { "POVRCE" },
new List<string> { "BASTA" }));

            A.Add(new Ass(
"COCA COLA",
"PEPSI",
"JOY",
"PARADAJZ",
new List<string> { "SOK"
   },
"DZEMPER",
"PCELA",
"DETELINA",
"KAKTUS",
new List<string> { "BROS" },
"POSLASTICARA",
"CASNA",
"CARI",
"ANDJA",
new List<string> { "SESTRA","SESTRE" },
"SLOMLJENA",
"SRZ",
"DO",
"Ca", new List<string> { "KOSKA","KOSKE" },
new List<string> { "VISNJA" }));

            A.Add(new Ass(
"MARICA",
"OTAC",
"JELKA",
"DISIC",
new List<string> { "DEJAN"
   ,"DEKI"},
"DUVANSKA",
"PEPKO",
"PAVLE",
"OTAC",
new List<string> { "MISKO" },
"SREDA",
"SUBOTA",
"CVET",
"ZITORADJA",
new List<string> { "PIJACA","PIJAC" },
"ROK",
"POP",
"NAROD",
"ZABAVA", new List<string> { "MUZIKA" },
new List<string> { "JBL" }));

            A.Add(new Ass(
"FETEL",
"BRZINA",
"STAZA",
"TRKA",
new List<string> { "FORMULA 1"
   ,"FORMULA"},
"SLATKIC",
"DEBELJKO",
"LJUBAV",
"DUPKO",
new List<string> { "JELKA","JELKIC" },
"MINHEN",
"JOCA",
"BERLIN",
"HITLER",
new List<string> { "NEMACKA" },
"BOLNICA",
"SPAVANJE",
"SVEST",
"SAN", new List<string> { "KOMA" },
new List<string> { "SUMAHER" }));

            A.Add(new Ass(
 "HLADNO",
 "ZIMA",
 "VODA",
 "DOBA",
 new List<string> { "LED"
   ,"LEDENO"},
 "LAV",
 "MUZIKA",
 "KOSA",
 "KONJ",
 new List<string> { "REP" },
 "STA RADIS",
 "KAKO SI",
 "ISTOCNO",
 "?",
 new List<string> { "PITANJE","PITATI" },
 "VECE",
 "DAN",
 "JUTRO",
 "COVEK", new List<string> { "DOBAR" },
 new List<string> { "AJS NIGRUTIN","AJS","NIGRUTIN" }));

            A.Add(new Ass(
"A",
"",
"C",
"D",
new List<string> { "B"
   ,"BE"},
"BOJKOT",
"FARMACIJA",
"JOCA",
"SEKA",
new List<string> { "ANDJELA","ANDJA" },
"EKSPLOZIJA",
"MILE KITIC",
"ATOM",
"RAT",
new List<string> { "BOMBA" },
"ZELENA",
"VOCE",
"CEZAR",
"BASTA", new List<string> { "SALATA" },
new List<string> { "VITAMIN","VITAMINI" }));

            A.Add(new Ass(
"CELE KULA",
"KUCA",
"TVRDJAVA",
"GRAD",
new List<string> { "NIS"},
"SLIKA",
"KINA",
"BERLIN",
"PLAC",
new List<string> { "ZID" },
"LAV",
"MAJMUN",
"PEPIC",
"SLON",
new List<string> { "ZIVOTINJA","ZIVOTINJE" },
"DECIJA",
"SPAVACA",
"DNEVNA",
"22", new List<string> { "SOBA" },
new List<string> { "KONJ" }));

            A.Add(new Ass(
"KAJSIJA",
"DUNJA",
"SLJIVA",
"DOMACA",
new List<string> { "RAKIJA"},
"BAMBUS",
"SPRICER",
"BELO",
"CRNO",
new List<string> { "VINO" },
"PISTOLJ",
"EKSPLOZIV",
"METAK",
"PUSKA",
new List<string> { "BARUT" },
"TUBORG",
"LAV",
"JELEN",
"ZAJECAR", new List<string> { "PIVO" },
new List<string> { "BURE" }));
            A.Add(new Ass(
"KAPRICOZA",
"ITALIJA",
"PECURKE",
"DOMACA",
new List<string> { "PICA"
   ,"PIZZA"},
"RAZVIJATI",
"STRANI",
"DOMACI",
"BIOSKOP",
new List<string> { "FILM" },
"GOVEDINA",
"PILE",
"SVINJA",
"JAGNJE",
new List<string> { "MESO" },
"KOZA",
"KRAVA",
"MLEKO",
"RUPE", new List<string> { "SIR" },
new List<string> { "BUREK" }));

            A.Add(new Ass(
"ZUTI",
"PEKING",
"KORONA",
"NAROD",
new List<string> { "KINA"},
"GAZIRANI",
"DOMACI",
"PEPSI",
"JOY",
new List<string> { "SOK" },
"BELO",
"CRNO",
"GROZDJE",
"BURE",
new List<string> { "VINO" },
"GRAD",
"TVRDJAVA",
"KONJ",
"PANDA", new List<string> { "NIS" },
new List<string> { "BAMBUS" }));

            A.Add(new Ass(
"KOSTI",
"SLOMLJENA",
"EVA",
"ADAM",
new List<string> { "REBRA"
   ,"REBRO"},
"SUNCOKRET",
"MASLINA",
"JAJA",
"TIGANJ",
new List<string> { "ULJE" },
"PUNO",
"MASINA",
"VODA",
"KONDENZACIJA",
new List<string> { "PARA" },
"ISPUSTANJE",
"GUMA",
"DISANJE",
"VODA", new List<string> { "VENTIL" },
new List<string> { "RADIJATOR" }));

            A.Add(new Ass(
"DLAKE",
"DEPILACIJA",
"KROKODIL",
"ZMIJA",
new List<string> { "KOZA"},
"DECEMBAR",
"NOVEMBAR",
"SEPTEMBAR",
"OKTOBAR",
new List<string> { "JESEN" },
"JANUAR",
"FEBRUAR",
"MART",
"CAROLIJE",
new List<string> { "ZIMA" },
"GLAVA",
"DUKS",
"KAPA",
"HLADNOCA", new List<string> { "KAPULJACA" },
new List<string> { "JAKNA" }));
            A.Add(new Ass(
"1+1+1",
"PRSTA",
"CARI",
"2+1",
new List<string> { "TRI"
   ,"3"},
"LISCE",
"BOJA",
"SUNCE",
"KINEZI",
new List<string> { "ZUTO","ZUTI","ZUT" },
"ODELO",
"CRNO",
"ZIMA",
"VINO",
new List<string> { "BELO","BEO" },
"JUTRO",
"OBROK",
"KREVET",
"PRZENICE", new List<string> { "DORUCAK" },
new List<string> { "JAJA","JAJE" }));

            A.Add(new Ass(
"ANZUJSKA",
"J",
"ZENSKO",
"IME",
new List<string> { "JOVANA"},
"NECU",
"NISAM",
"NOT",
"NE",
new List<string> { "NEGACIJA" },
"NAROD",
"EP",
"ZABAVA",
"LJUBAV",
new List<string> { "PESMA","PESME" },
"SRCE",
"OSECANJA",
"EMOCIJE",
"SVE ZA..", new List<string> { "LJUBAV" },
new List<string> { "NISAM TE ZBOG LEPOTE VOLEO" }));


            A.Add(new Ass(
"PALICA",
"AUTO",
"5",
"6",
new List<string> { "GOLF" },
"PO",
"5",
"ANTOMIN",
"VELIKO",
new List<string> { "MALO","MALI","MALA" },
"REP",
"SLEPI",
"RUPA",
"SIR",
new List<string> { "MIS" },
"SVECANA",
"MATURA",
"ODECA",
"KOLENA", new List<string> { "SUKNJA" },
new List<string> { "MINI" }));

            A.Add(new Ass(
"24 MART",
"DRVO",
"BFF",
"FARMACIJA",
new List<string> { "CEKI","CEROVINA" },
"KARTE",
"VIDEO",
"DRUSTVENA",
"DECIJA",
new List<string> { "IGRA","IGRICA" },
"DEVOJCICA",
"MUSKARAC",
"MOMAK",
"MALI",
new List<string> { "DECAK","DECKO" },
"BELI",
"ZUTI",
"ANJA",
"PROTEZA", new List<string> { "ZUBI","ZUB" },
new List<string> { "ZEC","ZEKA" }));

            A.Add(new Ass(
"KOSTI",
"MAGARAC",
"KOZA",
"KRAVA",
new List<string> { "MLEKO" },
"DORUCAK",
"PSENICA",
"KUKURUZ",
"BRASNO",
new List<string> { "KACAMAK" },
"ZA PONETI",
"TRON",
"PASTA",
"NAJT AND DAJ",
new List<string> { "POKUPITI","POKUPIO" },
"HLEB",
"ZEMICKA",
"PLJEKSAVICA",
"NOZ", new List<string> { "LEPINJA" },
new List<string> { "KAJMAK" }));
            A.Add(new Ass(
"PRA",
"LJUBINKA",
"DEDA",
"MARICA",
new List<string> { "BABA","BAKA" },
"CARI",
"1",
"2",
"",
new List<string> { "TRI","3" },
"CRVENO",
"CRNO",
"SO",
"ZUTO",
new List<string> { "MORE" },
"7",
"JANUAR",
"KATOLICKI",
"ISUS", new List<string> { "BOZIC" },
new List<string> { "PRASE","PRASAC","PRASICI" }));

            A.Add(new Ass(
"500",
"ITALIJA",
"TORINO",
"BRAVO",
new List<string> { "FIAT","FIJAT" },
"MATICAR",
"CRKVA",
"KAFANA",
"SLIKANJE",
new List<string> { "SVADBA","VENCANJE" },
"SV SAVA",
"HEJ SLOVENI",
"BOZE PRAVDE",
"LIJEPA NASA",
new List<string> { "HIMNA" },
"LEPA",
"SNEG",
"KUGA",
"ITALIJA", new List<string> { "BELA","BELO","BEO" },
new List<string> { "ZASTAVA","ZASTAVE" }));

            A.Add(new Ass(
"SAH",
"ELIZABETA",
"RAPSODIJA",
"FRED MERCURY",
new List<string> { "QUEEN","KRALJICA","KRALJ" },
"CASOVI",
"5 MIN",
"15 MIN",
"MUZIKA",
new List<string> { "PAUZA","PAUZIRATI" },
"RAZVIJATI",
"HOROR",
"KOMEDIJA",
"AKCIJA",
new List<string> { "FILM" },
"VOJNIK",
"SVRSEN",
"RITUAL",
"OFICIR", new List<string> { "CIN" },
new List<string> { "DRAMA","DRAMITI" }));

            A.Add(new Ass(
"100",
"TENIS",
"SLAVA",
"KAFIC",
new List<string> { "STO" },
"ZEMLJA",
"PLANETA",
"SLADOLED",
"BACANJE",
new List<string> { "KUGLA" },
"SIR",
"ASFALT",
"GOLF",
"MIS",
new List<string> { "RUPA","RUPE" },
"DRVO",
"PECANJE",
"CAROBNJAK",
"STARAC", new List<string> { "STAP","STAPIC" },
new List<string> { "BILIJAR" }));

            A.Add(new Ass(
"KASTING",
"OSKAR",
"FILM",
"KOJO",
new List<string> { "GLUMAC" },
"SV SAVA",
"SRBIJA",
"PRVOVENCANI",
"ISTORIJA",
new List<string> { "VUKAN NEMANJIC" },
"VAMPIR",
"ZAOSTRITI",
"DRVO",
"NOZ",
new List<string> { "KOLAC" },
"GROBLJE",
"KOVCEG",
"SMRT",
"LADAN", new List<string> { "PREMINUO","MRTAV" },
new List<string> { "NEBOJSA GLOGOVAC","GLOGOVAC" }));

            A.Add(new Ass(
"ANJA",
"ZUBI",
"JELKA",
"NOGA",
new List<string> { "PROTEZA" },
"SMART",
"BROJ",
"MOBILNI",
"BROJCANIK",
new List<string> { "TELEFON" },
"OGRANICENJE",
"GLUP",
"BEZ",
"NEOGRANICENJE",
new List<string> { "LIMIT" },
"PROIZVOD",
"DINARI",
"AKCIJA",
"EVRO", new List<string> { "CENA" },
new List<string> { "FIKSNO","FIKSNI" }));

            A.Add(new Ass(
"MAKAZE",
"MASINICA",
"STOLICA",
"KOSA",
new List<string> { "FRIZER" },
"VIDEO",
"SLIKA",
"APARAT",
"MAN",
new List<string> { "FOTO","PHOTO" },
"A",
"",
"C",
"D",
new List<string> { "B","BE" },
"KOMEDIJA",
"ROMANTIKA",
"DRAMA",
"AKCIJA", new List<string> { "FILM" },
new List<string> { "STUDIO" }));

            A.Add(new Ass(
"TEZINA",
"NJUTN",
"AKCIJA",
"REAKCIJA",
new List<string> { "SILA" },
"SEVER",
"JUG",
"ZAPAD",
"ISTOK",
new List<string> { "KOMPAS" },
"MEKARTNI",
"LED",
"SANTA",
"PINGVINI",
new List<string> { "POL" },
"VRATA",
"HLADNO",
"KOMORA",
"LED", new List<string> { "FRIZIDER" },
new List<string> { "MAGNET" }));

            A.Add(new Ass(
"KONJ",
"META",
"LUDILA",
"EPI",
new List<string> { "CENTAR" },
"A*B",
"A*A",
"A*H/2",
"FIGURA",
new List<string> { "POVRSINA","P" },
"VELIKA",
"KATERINA",
"GRUPA",
"SRCE",
new List<string> { "EKV" },
"DJAVO",
"DANTE",
"9",
"RAJ", new List<string> { "PAKAO" },
new List<string> { "KRUG" }));

            A.Add(new Ass(
"KAPULJACA",
"PERJE",
"ZIMA",
"JESEN",
new List<string> { "JAKNA" },
"DRZAVA",
"TRAMP",
"NJUJORK",
"AMERIKA",
new List<string> { "SAD" },
"DVOBOJ",
"SESIR",
"OK KORAL",
"OBRACUN",
new List<string> { "KAUBOJ" },
"IGRA",
"BLEFIRANJE",
"KARTE",
"KAZINO", new List<string> { "POKER" },
new List<string> { "TEKSAS","TEXAS" }));

            A.Add(new Ass(
"POZIV",
"FIKSNI",
"BROJ",
"MOBILNI",
new List<string> { "TELEFON" },
"UGAO",
"SVETLO",
"SIJALICA",
"STO",
new List<string> { "LAMPA" },
"H2S04",
"H2S03",
"HCL",
"H3P04",
new List<string> { "KISELINA","KISELINE" },
"DUGME",
"KAPIJA",
"TV",
"KLIMA", new List<string> { "DALJINSKI" },
new List<string> { "BATERIJA","BATERIJE" }));

            A.Add(new Ass(
"RUZAN",
"DEBEO",
"DOSADAN",
"NERVOZA",
new List<string> { "PEPIC","PEPKO" },
"KAUC",
"TV",
"SVETLOST",
"BORAVAK",
new List<string> { "DNEVNA SOBA","SOBA" },
"HRIST",
"JERUSALIM",
"BOG",
"SIN",
new List<string> { "ISUS","ISUS HRIST" },
"DORUCAK",
"RUCAK",
"UZINA",
"DNEVNI", new List<string> { "OBROK" },
new List<string> { "TAJNA VECERA" }));

            A.Add(new Ass(
"LUNA",
"KLUPA",
"ZELENI",
"SV SAVA",
new List<string> { "PARK" },
"ZGODNIC",
"LEPOTANKO",
"SLATKO",
"PRIJATNO",
new List<string> { "JELKIC","JELKA"},
"CRVENKAPA",
"VES",
"RINGISPIL",
"SMECE",
new List<string> { "KORPA" },
"CVECE",
"PAPRIKA",
"STAKLO",
"KROMPIR", new List<string> { "BASTA" },
new List<string> { "LJULJASKA","LJULJANJE" }));
            A.Add(new Ass(
"6S",
"7",
"TELEFON",
"JOCA",
new List<string> { "AJFON","IPHONE" },
"MAMAC",
"PIJAVICA",
"PECANJE",
"INSEKT",
new List<string> { "CRV" },
"KISELA",
"AMERIKA",
"LENJA",
"KO .. NE SKITA",
new List<string> { "PITA" },
"ZAKON",
"ISAK",
"SILA",
"N", new List<string> { "NJUTN" },
new List<string> { "JABUKA" }));

            A.Add(new Ass(
"KRIT",
"KRF",
"USKRS",
"POLU",
new List<string> { "OSTRVO","OSTRVA" },
"SOK",
"TECNOST",
"OSVEZAVAJUCI",
"KAFA",
new List<string> { "NAPITAK" },
"SMRDE",
"KARTON SITI",
"ROMI",
"CRNI",
new List<string> { "CIGANI" },
"BANANA",
"KRUSKA",
"JABUKA",
"POMARANDZA", new List<string> { "VOCE" },
new List<string> { "LIMUNADA" }));

            A.Add(new Ass(
"SELO",
"PSENICA",
"HRANA",
"KRAVA",
new List<string> { "SLAMA","SENO" },
"REP",
"CEKI",
"ZUBI",
"USI",
new List<string> { "ZEC" },
"SMESAN",
"CIRKUS",
"NOS",
"SATOR",
new List<string> { "KLOVN" },
"ZAPAD",
"TEKSAS",
"OBRACUN",
"INDIJANCI", new List<string> { "KAUBOJ","KAUBOJI" },
new List<string> { "SESIR" }));

            A.Add(new Ass(
"NAPORAN",
"RUZAN",
"GLUP",
"DOSADAN",
new List<string> { "PEPIC","PEPKO" },
"SPAVANJE",
"DNEVNA",
"VRATA",
"KUCA",
new List<string> { "SOBA","SOBE" },
"CANJ",
"BUDVA",
"KOTOR",
"MORE",
new List<string> { "JADRAN","JADRANSKO" },
"PRELAZ",
"KRAJINA",
"GORNJA",
"DONJA", new List<string> { "GRANICA" },
new List<string> { "PAPUCA","PAPUCAR" }));

            A.Add(new Ass(
"KRAVA",
"ROGOVI",
"SPANIJA",
"GOVEDO",
new List<string> { "BIK" },
"PECENJE",
"PICA",
"SPORET",
"METAL",
new List<string> { "PLEH" },
"ZUBA",
"IZMEDJU",
"SPACE",
"BLANKO",
new List<string> { "RAZMAK" },
"PADEZ",
"4",
"KOGA",
"CEGA", new List<string> { "AKUZATIV" },
new List<string> { "VOLIM TE" }));

            A.Add(new Ass(
"VELIKI",
"MRAV",
"AFRIKA",
"PRIDEV",
new List<string> { "MALI","MALO","MALA" },
"SARENA",
"VRATA",
"DETE",
"KRAVA",
new List<string> { "TELE" },
"EMISIJA",
"TV",
"JOVANA ",
"DEA",
new List<string> { "VODITELJ","VODITELJI" },
"LUKAS",
"DJANI",
"KEBA",
"TOPALKO", new List<string> { "PEVAC","PEVACI" },
new List<string> { "MIKROFON" }));

            A.Add(new Ass(
"POSLASTICARA",
"DISKE",
"DISIC",
"TATA",
new List<string> { "DEKI", "DEJAN" },
"AU",
"BELO",
"POLUGA",
"MOJE",
new List<string> { "ZLATO" },
"SEDISTE",
"TOCKOVI",
"VOLAN",
"BMX",
new List<string> { "BICIKLA", "BICIKL" },
"TRUP",
"GLAVA",
"TIROKSIN",
"GRKLJAN", new List<string> { "VRAT" },
new List<string> { "LANAC","LANCI" }));

            A.Add(new Ass(
"PRUGA",
"MRAK",
"KOPATI",
"VOZ",
new List<string> { "TUNEL" },
"PRSTI",
"KOSA",
"PRIDEV",
"NOGE",
new List<string> { "DUGO" },
"NOGE",
"SLATKO",
"KOSA",
"PRIDEV",
new List<string> { "KRATKO","KRATAK" },
"ZIVOTINJE",
"ZELENILO",
"BILJKE",
"EKOLOGIJA", new List<string> { "PRIRODA" },
new List<string> { "SVETLO","SVETLOST" }));

            A.Add(new Ass(
"PRAVOSLAVNA",
"CRKVA",
"ROK",
"MUZIKA",
new List<string> { "POP" },
"GLUP",
"RUZAN",
"DEBEO",
"DOSADAN",
new List<string> { "PEPIC","PEPKO" },
"MUSKA",
"KOZA",
"ROGOVI",
"ZNAK",
new List<string> { "JARAC", "JARE" },
"KOSA",
"JEZIK",
"GUSTA",
"SEDA", new List<string> { "DLAKA" },
new List<string> { "BRADA" }));

            A.Add(new Ass(
"VOJSKA",
"JELKIC",
"DISKE",
"OTAC",
new List<string> { "DEJAN", "DEKI" },
"NAKOVANJ",
"UZENGIJA",
"CEKIC",
"APARAT",
new List<string> { "USI","UVO" },
"PRVA",
"PINK",
"B92",
"RTS",
new List<string> { "TV","TELEVIZIJA" },
"NJEMACKA",
"ANDJA",
"ZET",
"FRANKFURT", new List<string> { "JOCA", "JOVICA" },
new List<string> { "KANAL","KANALI" }));

            A.Add(new Ass(
"ZUTO",
"Au",
"LANAC",
"BELO",
new List<string> { "ZLATO", "ZLATNI", "ZLATAN" },
"MIR",
"ODELO",
"SNEG",
"BOJA",
new List<string> { "BELO","BELI","BEO" },
"AUTO",
"ZAPREZNA",
"GUMA",
"PREVOZ",
new List<string> { "KOLA", "AUTOMOBIL" },
"OKO",
"ZUTO",
"BELO",
"USKRS", new List<string> { "JAJE", "JAJA" },
new List<string> { "KOKA" }));

            A.Add(new Ass(
"VES",
"LETO",
"RUKAVI",
"POLO",
new List<string> { "MAJICA", "MAJCA" },
"GRKLJAN",
"TRUP",
"GLAVA",
"OGRLICA",
new List<string> { "VRAT" },
"KOMUNIZAM",
"PUTIN",
"KUHINJA",
"MOSKVA",
new List<string> { "RUSIJA" },
"MADRID",
"BARSELONA",
"MONARHIJA",
"MALAGA", new List<string> { "SPANIJA" },
new List<string> { "KRAGNA" }));

            A.Add(new Ass(
"CRVENO",
"PLAVO",
"BELO",
"DRZAVA",
new List<string> { "ZASTAVA" },
"MASLINA",
"PISMO",
"GLINA",
"PTICA",
new List<string> { "GOLUB" },
"ZUBI",
"BOJA",
"ODELO ",
"MARAMICA",
new List<string> { "BELA", "BELO" },
"BALKAN",
"PRVI",
"DRUGI",
"SVETSKI", new List<string> { "RAT" },
new List<string> { "MIR" }));

            A.Add(new Ass(
"HEMIJSKA",
"BRISANJE",
"OLOVKA",
"KOSA",
new List<string> { "GUMICA", "GUMA" },
"DOPTRIJA",
"VID",
"SUNCE",
"STAKLO",
new List<string> { "NAOCARE" },
"PROZOR",
"RAZBITI",
"PESAK",
"Si",
new List<string> { "STAKLO", "STAKLENI" },
"PCELA",
"USNE",
"SLATKO",
"GROZDJE", new List<string> { "MED", "MEDENA" },
new List<string> { "TEGLA" }));

            A.Add(new Ass(
"SVILA",
"PAPIR",
"DZEP",
"NOS",
new List<string> { "MARAMICA" },
"OLOVKE",
"BOJICE",
"SKOLA",
"PERNICA",
new List<string> { "FUTROLA" },
"BOLT",
"SVETLOST",
"KM/H",
"M/S",
new List<string> { "BRZINA" },
"SLIKA",
"MEMORIJA",
"OKVIR",
"REKET", new List<string> { "RAM" },
new List<string> { "NAOCARE" }));

            A.Add(new Ass(
"DZEK RASEL",
"ASTOR",
"MAKS",
"DONI",
new List<string> { "PAS" },
"POLUGA",
"BELO",
"AU",
"PRSTEN",
new List<string> { "ZLATO","ZLATNO","ZLATNI" },
"NARUKVICA",
"AG",
"NAKIT ",
"SIVO",
new List<string> { "SREBRO", "SREBRNA" },
"UGLJENIK",
"RUDNIK",
"KRV",
"KRISTAL", new List<string> { "DIJAMANT" },
new List<string> { "OGRLICA" }));

            A.Add(new Ass(
"OCI",
"GLAVA",
"BLEDO",
"LEPO",
new List<string> { "LICE", "FACA" },
"GOL",
"PECANJE",
"SPAJDERMEN",
"PAUK",
new List<string> { "MREZA" },
"ANFAS",
"LEVI",
"DESNI",
"IZ",
new List<string> { "PROFIL", "PROFILA" },
"O DZUNGLI",
"ROMAN",
"PESMA",
"UDZBENIK", new List<string> { "KNJIGA" },
new List<string> { "FACEBOOK","FEJSBUK" }));
            A.Add(new Ass(
           "MAGARAC",
           "Ca",
           "SIR",
           "KRAVA",
           new List<string> { "MLEKO" },
           "AVGUST",
           "JUL",
           "DOBA",
           "JE",
           new List<string> { "LETO" },
           "DOM",
           "DISICI",
           "DJORDJEVICI",
           "GLAVA",
           new List<string> { "PORODICA" },
           "USB",
           "RACUNAR",
           "MEMORIJA",
           "BOMBA", new List<string> { "FLESKA", "FLASH","FLES" },
           new List<string> { "SLADOLED" }));

            A.Add(new Ass(
"45",
"ODMOR",
"ZVONO",
"SKOLA",
new List<string> { "CAS" },
"BB",
"7. JULI",
"TROTOAR",
"POBEDINA",
new List<string> { "ULICA" },
"SKOLA",
"JELKA",
"STEPENICE",
"TAKMICENJE",
new List<string> { "CICKOVA", "CICKO" },
"BUS",
"NIS ESKPRES",
"RADIO",
"PETNICA", new List<string> { "STANICA" },
new List<string> { "POLICIJA" }));

            A.Add(new Ass(
"UDICA",
"REKA",
"STAP",
"RIBA",
new List<string> { "PECANJE", "PECATI" },
"ZELENA",
"AJDARED",
"DELISES",
"VOCE",
new List<string> { "JABUKA" },
"KOBILA",
"VISNJA",
"ZUB",
"SUPLJE",
new List<string> { "TRULA", "TRULO" },
"OSNOV",
"LICE",
"VERA",
"TVRDI", new List<string> { "SUMNJA", "SUMNJATI" },
new List<string> { "CRV" }));

            A.Add(new Ass(
"SARGAREPA",
"ZUBI",
"EDI MARFI",
"REP",
new List<string> { "MAGARAC", "MAGARE" },
"KRUNA",
"MAJKA",
"ZENA",
"SRCA",
new List<string> { "KRALJICA","CARICA" },
"SIR",
"KRAVA",
"KOZA ",
"Ca",
new List<string> { "MLEKO" },
"RIM",
"KOCKA",
"SALATA",
"GAJ", new List<string> { "CEZAR" },
new List<string> { "KLEOPATRA" }));

            A.Add(new Ass(
"POLICAJAC",
"NEBO",
"KOSA",
"OKO",
new List<string> { "PLAVO","PLAVI" },
"BEZICNI",
"JBL",
"AUTOMOBIL",
"KOMPJUTER",
new List<string> { "ZVUCNIK" },
"BUKA",
"LEKAR",
"MUZIKA",
"STETOSKOP",
new List<string> { "SLUSALICE"},
"BELI",
"ZUTI",
"USTA",
"OCNJAK", new List<string> { "ZUB","ZUBI" },
new List<string> { "BLUETOOTH","BLUETOOT","BLUTUT" }));

            A.Add(new Ass(
"SV JOVAN",
"SV SAVA",
"SV LUKA",
"SV NIKOLA",
new List<string> { "SLAVA","SLAVE" },
"BACENA",
"MATEMATIKA",
"GEOMETRIJA",
"IVICA",
new List<string> { "KOCKA" },
"DLAN",
"PRST",
"IGRATI SE",
"KO ZNA STA LI JE",
new List<string> { "SUDBINA" },
"LATICA",
"TRN",
"CRVENA",
"MAJKA", new List<string> { "RUZA","RUZICA","RUSKA" },
new List<string> { "KOLAC","KOLACI" }));

            A.Add(new Ass(
"TEHNICAR",
"CEKIC",
"MREZA",
"PRIMAC",
new List<string> { "ODBOJKA" },
"LONDON",
"SKAZALJKE",
"DZEP",
"ZID",
new List<string> { "SAT" },
"PRIDEV",
"BLATO",
"MRTVO",
"PRIRODA",
new List<string> { "ZIVI", "ZIVA","ZIVO" },
"ORGAN",
"KAMEN",
"DVA",
"TRANSPLATACIJA", new List<string> { "BUBREG","BUBREZI" },
new List<string> { "PESAK" }));

            A.Add(new Ass(
"KUCA",
"CIGLA",
"PENDZER",
"STAKLO",
new List<string> { "PROZOR" },
"CIGARE",
"VULKAN",
"DUVAN",
"VATRA",
new List<string> { "DIM" },
"TUS",
"SPRINGFILD",
"PRESVLACENJE",
"OGLEDALO",
new List<string> { "KABINA" },
"ATELJE 212",
"DASKE",
"GLUMCI",
"NARODNO", new List<string> { "POZORISTE" },
new List<string> { "ZAVESA" }));

            A.Add(new Ass(
"HRANA",
"KUVAR",
"RUSIJA",
"SERIJA",
new List<string> { "KUHINJA" },
"EVRO",
"DOLARI",
"BOGASTVO","" +
"PARE",
new List<string> { "NOVAC" },
"KOMERCIJALNA",
"UNICREDIT",
"AIK",
"INTESA",
new List<string> { "BANKA" },
"FILIP MORIS",
"IBM",
"KOMPANIJA",
"ODELJENJE", new List<string> { "FIRMA" },
new List<string> { "SEF" }));

            A.Add(new Ass(
"SPORET",
"KUVANJE",
"METALAC",
"LONAC",
new List<string> { "SERPA" },
"SNEG",
"FEBRUAR",
"JANUAR",
"DOBA",
new List<string> { "ZIMA" },
"OCI",
"POVRCE",
"ZEC",
"MAGARAC",
new List<string> { "SARGAREPA" },
"KALIPSO",
"CMOK",
"LENI",
"RUMENKO", new List<string> { "SLADOLED" },
new List<string> { "SNESKO BELIC","SNESKO" }));

            A.Add(new Ass(
"KANDZE",
"KRALJ",
"REP",
"GRIVA",
new List<string> { "LAV" },
"KOZA",
"PLUCA",
"BUBREG",
"CULA",
new List<string> { "ORGAN","ORGANI" },
"INSTRUMENT",
"ZICE",
"GUDALO",
"MUZIKA",
new List<string> { "VIOLINA" },
"USNE",
"SECER",
"TOPALKO",
"PCELA", new List<string> { "MED","MEDENA" },
new List<string> { "SRCE" }));
            A.Add(new Ass(
           "ORUZJE",
           "KASARNA",
           "UNIFORMA",
           "SRBIJA",
           new List<string> { "VOJSKA" },
           "SAMI",
           "ZIVOTINJE",
           "JAGODINA",
           "BEOGRAD",
           new List<string> { "ZOO VRT","ZOO" },
           "MUZIKA",
           "KONJ",
           "ZMAJ",
           "MACKA",
           new List<string> { "REP" },
           "PRIRODA",
           "TRAVA",
           "LIVADA",
           "MUSLIMANI", new List<string> { "ZELENI","ZELENA" },
           new List<string> { "GUSTER" }));

            A.Add(new Ass(
"IGRA",
"BACENA",
"KVADRATI",
"TELO",
new List<string> { "KOCKA" },
"TENIS",
"OKRUGLI",
"NOGARE",
"100",
new List<string> { "STO" },
"1371",
"REKA",
"BAJKA",
"BABA",
new List<string> { "MARICA" },
"JABUKA",
"GRDANA",
"BAJKA",
"BABA", new List<string> { "VESTICA" },
new List<string> { "IVICA" }));

            A.Add(new Ass(
"KOLENO",
"SPORT",
"NOGA",
"POVREDA",
new List<string> { "STEZNIK","STEZNICI" },
"MREZA",
"STO",
"REKET",
"NOVAK",
new List<string> { "TENIS" },
"DZOINT",
"UGANUCE",
"RUKA",
"IZVRNUTI",
new List<string> { "ZGLOB" },
"TRICEPS",
"RAME",
"SAKA",
"BICEPS", new List<string> { "RUKA" },
new List<string> { "LAKAT" }));

            A.Add(new Ass(
"VOLAN",
"GUMA",
"LANAC",
"TOCKOVI",
new List<string> { "BICIKLA","BICIKL" },
"KANADA",
"SPORT",
"LED",
"PAK",
new List<string> { "HOKEJ" },
"AMERICKI",
"PEPIC",
"SPORT",
"LOPTA",
new List<string> { "FUDBAL" },
"VESPA",
"DOZVOLA",
"NA VODI",
"MOTOR", new List<string> { "SKUTER" },
new List<string> { "KACIGA" }));

            A.Add(new Ass(
"SEBET",
"SECER",
"JELKIC",
"KOLAC",
new List<string> { "SLADAK","SLATKO" },
"GARI",
"SPOR",
"GOLAC",
"KUCICA",
new List<string> { "PUZ" },
"NADIMAK",
"KROASAN",
"KREM",
"DZEM",
new List<string> { "KIFLA" },
"VELIKI",
"VES",
"PRANJE",
"PUDER", new List<string> { "PRASAK" },
new List<string> { "PECIVO" }));

            A.Add(new Ass(
"HITNA",
"HELP",
"POZIV",
"SOS",
new List<string> { "POMOC" },
"TRAKA",
"SAJLA",
"TEGOVI",
"KANGOO",
new List<string> { "TERETANA" },
"TUZAN",
"GOLI",
"SRECAN",
"KRAJ",
new List<string> { "ZIVOT" },
"SKOLA",
"REZERVE",
"VEZBA",
"BENCH", new List<string> { "KLUPA","KLUPE" },
new List<string> { "TRENER" }));

            A.Add(new Ass(
"REKA",
"H20",
"MORE",
"HLADNA",
new List<string> { "VODA" },
"TRBUSNJACI",
"PIVO",
"SALO",
"DEBEO",
new List<string> { "STOMAK","STOMACIC" },
"LEPOTANCIC",
"DEBELJANCIC",
"SLATKIC",
"ZGODNIC",
new List<string> { "DEMINUTIV" },
"NAPORAN",
"SMOR",
"RUZAN",
"JADAN", new List<string> { "PEPIC","PEPKO","PETAR" },
new List<string> { "PISTOLJCIC","PISTOLJCICI","PISTOLJ","PISTOLJI" }));

            A.Add(new Ass(
"NOKIA",
"SAMSUNG",
"FIKSNI",
"MOBILNI",
new List<string> { "TELEFON" },
"IDIOT",
"SLIKA",
"SVADBA",
"STUDIO",
new List<string> { "FOTOAPARAT","FOTO","APARAT" },
"ALO",
"NOVOSTI",
"NARODNE",
"POLITIKA",
new List<string> { "NOVINE", "NOVINA" },
"DUGO",
"KRATKO",
"SUNCE",
"TUNEL", new List<string> { "TUNEL" },
new List<string> { "BLIC" }));

            A.Add(new Ass(
"MORE",
"PLIMA",
"FALMINGOSI",
"PLAZA",
new List<string> { "OBALA" },
"JABUKA",
"5S",
"6S",
"7",
new List<string> { "AJFON","IPHONE" },
"NAJVISE",
"JELKIC",
"VOLI",
"MNOGO",
new List<string> { "PEPIC", "PEPKO" },
"WALLPAPER",
"SLIKA",
"KOMPJUTER",
"TELEFON", new List<string> { "POZADINA" },
new List<string> { "SVETIONIK" }));

            A.Add(new Ass(
"KESTEN",
"ZENICA",
"NAS",
"LONDON",
new List<string> { "OKO" },
"STAZA",
"STELLA",
"ASTRA",
"CRVENA",
new List<string> { "ZVEZDA" },
"MAJKA",
"BILJKA",
"LATICE",
"CRVENE",
new List<string> { "RUZA","RUZICA","RUSKA" },
"SECENJE",
"GRICKANJE",
"MAKAZE",
"LAKIRANJE", new List<string> { "NOKAT","NOKTI" },
new List<string> { "TRN" }));

            A.Add(new Ass(
"VOCE",
"SOK",
"KISELI",
"CITRUS",
new List<string> { "LIMUN" },
"LIST",
"TRAVA",
"PRIRODA",
"EKOLOGIJA",
new List<string> { "ZELENI","ZELENO","ZELEN" },
"JABUKA",
"BANANA",
"ANANAS",
"KRUSKA",
new List<string> { "VOCE" },
"MLEKO",
"WELLNES",
"ZLATNI PEK",
"KOLAC", new List<string> { "KEKS" },
new List<string> { "CAJ" }));

            A.Add(new Ass(
"ZUTO",
"BELO",
"CRNO",
"CRVENO",
new List<string> { "MORE" },
"BIOSKP",
"SO",
"ANDJELA",
"KUKURUZ",
new List<string> { "KOKICE" },
"SICUSNO",
"VELIKO",
"PRIDEV",
"PO",
new List<string> { "MALO", "MALI" },
"SPORET",
"PARTIJARSIJA",
"GRAD",
"KOSOVO", new List<string> { "PEC" },
new List<string> { "MIKROTALASNA" }));

            A.Add(new Ass(
"BRADA",
"DECKO",
"DJAKUS",
"ZGODAN",
new List<string> { "PEPIC","PEPKO" },
"DUPKO",
"TRBUSNJACI",
"SLATKIC",
"DEBELJKO",
new List<string> { "JELKIC","JELKA" },
"TRSAVA KOSA",
"NEMACKA",
"ZET",
"LALE",
new List<string> { "JOCA","JOVICA" },
"BOJKOT",
"FARMACIJA",
"SESTRA",
"SVASTIKA", new List<string> { "ANDJELA","ANDJA" },
new List<string> { "AJFON","IPHONE" }));

            A.Add(new Ass(
"PASTA",
"KOLOSEUM",
"RIM",
"VENECIJA",
new List<string> { "ITALIJA" },
"31",
"SRBIJA",
"KINA",
"KUTAK",
new List<string> { "NOVA GODINA" },
"SUNCE",
"LJUBOMORA",
"SVET",
"DZEMPER",
new List<string> { "ZUTO", "ZUT" },
"AHIL",
"5.",
"NOGA",
"BROJ", new List<string> { "PETA" },
new List<string> { "STIKLA","STIKLE" }));
            A.Add(new Ass(
"SLATKA",
"PAMETNA",
"LEPA",
"ZGODNA",
new List<string> { "JELKA","JELKIC" },
"BRADA",
"GUZONJA",
"DEBELJAN",
"DJAKUS",
new List<string> { "PEPIC","PEPKO" },
"DO",
"RE",
"FA",
"SOL",
new List<string> { "NOTA", "NOTE" },
"VI",
"TI ",
"JA",
"ON", new List<string> { "ZAMENICE","ZAMENICA" },
new List<string> { "MI" }));

            A.Add(new Ass(
"V",
"O",
"L",
"I",
new List<string> { "M" },
"T",
"E",
"",
"J",
new List<string> { "E" },
"L",
"K",
"O",
"",
new List<string> { "T" },
"V",
"O",
"J",
"", new List<string> { "PEPIC" },
new List<string> { "ZAUVEK" }));












        }
    }
}
